/**
 * @module whats-new/App
 *
 * What's New page — opened automatically by the background script
 * after the user updates the extension to a new version. Renders
 * the release notes for the current version that the build-time
 * script `extension/scripts/build-whats-new.mjs` extracted from
 * CHANGELOG.md and wrote to `/whats-new.json`.
 *
 * Accessibility notes:
 *   - The page H1 receives focus on mount (via ref + rAF) so screen
 *     readers announce the heading text immediately. The skip link
 *     in index.html bypasses the header and lands on the release
 *     notes region for keyboard users.
 *   - There is intentionally no aria-live announcement on load —
 *     focusing the H1 already triggers a virtual-cursor read of the
 *     heading. A live region would double-announce.
 *   - The action buttons sit inside <nav aria-label="Page actions">
 *     so screen reader users can jump straight to them via the
 *     landmark.
 *   - The full-changelog link in the footer carries the absolute
 *     GitHub URL because there is no in-extension full changelog
 *     view; this matches the pattern used by the version footer
 *     on the options page (entrypoints/options/App.tsx).
 *
 * The HTML inside whats-new.json is generated by our own build
 * script from a CHANGELOG file the maintainer commits, so
 * dangerouslySetInnerHTML is safe in this context. The build script
 * escapes user content before adding trusted tags.
 */

import { useEffect, useRef, useState } from "react";
import { Button } from "@/components/ui/button";

interface WhatsNewPayload {
  version: string;
  html: string;
  generatedAt: string;
}

const MANIFEST = browser.runtime.getManifest();
const EXTENSION_NAME = MANIFEST.name;
const FULL_CHANGELOG_URL = "https://github.com/akash07k/butterswitch/blob/main/CHANGELOG.md";

/** Read the `from` query parameter (the version the user updated from). */
function readPreviousVersion(): string | null {
  try {
    const params = new URLSearchParams(window.location.search);
    return params.get("from");
  } catch {
    return null;
  }
}

/** Page status — drives what the body renders. */
type Status = "loading" | "ready" | "error";

/**
 * Page root. Fetches whats-new.json on mount, focuses the H1 once
 * the data is in (so the SR reads the heading rather than a stale
 * "Loading..." string), and renders the release notes plus a small
 * action bar.
 */
export default function App() {
  const [status, setStatus] = useState<Status>("loading");
  const [payload, setPayload] = useState<WhatsNewPayload | null>(null);
  const [errorMessage, setErrorMessage] = useState<string>("");
  const headingRef = useRef<HTMLHeadingElement>(null);
  const previousVersion = readPreviousVersion();

  useEffect(() => {
    let cancelled = false;
    async function load() {
      try {
        const url = browser.runtime.getURL("/whats-new.json");
        const response = await fetch(url);
        if (!response.ok) {
          throw new Error(`HTTP ${response.status}`);
        }
        const data = (await response.json()) as WhatsNewPayload;
        if (cancelled) return;
        setPayload(data);
        setStatus("ready");
      } catch (error) {
        if (cancelled) return;
        setErrorMessage(error instanceof Error ? error.message : String(error));
        setStatus("error");
      }
    }
    load();
    return () => {
      cancelled = true;
    };
  }, []);

  // Move focus to the H1 once the heading text is final. We wait
  // until status changes off "loading" so the SR reads the real
  // version line, not the placeholder.
  useEffect(() => {
    if (status === "loading") return;
    requestAnimationFrame(() => {
      headingRef.current?.focus();
    });
  }, [status]);

  const handleClose = () => {
    window.close();
  };

  const handleOpenSettings = () => {
    browser.runtime.openOptionsPage();
    window.close();
  };

  const headingText =
    status === "ready" && payload
      ? `What's new in ${EXTENSION_NAME} v${payload.version}`
      : `What's new in ${EXTENSION_NAME}`;

  return (
    <>
      <header className="max-w-3xl mx-auto p-6 pb-2">
        <h1 ref={headingRef} tabIndex={-1} className="text-2xl font-bold">
          {headingText}
        </h1>
        {previousVersion && status === "ready" && payload && (
          <p className="text-sm text-muted-foreground mt-2">
            Updated from v{previousVersion} to v{payload.version}.
          </p>
        )}
      </header>

      <main id="release-notes" className="max-w-3xl mx-auto px-6 pb-4">
        {status === "loading" && (
          <p role="status" className="text-muted-foreground">
            Loading release notes...
          </p>
        )}

        {status === "error" && (
          <div role="alert" className="space-y-2">
            <h2 className="text-lg font-semibold">Could not load release notes</h2>
            <p className="text-muted-foreground">{errorMessage}</p>
            <p>
              Read the latest release notes on GitHub:{" "}
              <a
                href={FULL_CHANGELOG_URL}
                rel="noopener noreferrer"
                className="underline hover:no-underline focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2"
              >
                {FULL_CHANGELOG_URL}
              </a>
              .
            </p>
          </div>
        )}

        {status === "ready" && payload && (
          // The HTML comes from our own build-time markdown converter
          // running over the maintainer-committed CHANGELOG.md. User
          // input never reaches this string, and the converter escapes
          // every unescaped < / > / & before adding our trusted tags.
          <div
            className="whats-new-prose space-y-3"
            dangerouslySetInnerHTML={{ __html: payload.html }}
          />
        )}
      </main>

      <nav aria-label="Page actions" className="max-w-3xl mx-auto px-6 pb-4 flex gap-2 flex-wrap">
        <Button onClick={handleOpenSettings}>Open Settings</Button>
        <Button variant="outline" onClick={handleClose}>
          Close
        </Button>
      </nav>

      <footer
        role="contentinfo"
        aria-label="About this page"
        className="max-w-3xl mx-auto px-6 pb-6 pt-2 mt-4 border-t border-border text-sm text-muted-foreground"
      >
        <p>
          Looking for older releases?{" "}
          <a
            href={FULL_CHANGELOG_URL}
            rel="noopener noreferrer"
            className="underline hover:no-underline focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2"
          >
            Read the full changelog on GitHub
          </a>
          .
        </p>
        <p className="mt-1">
          You can turn off the What&apos;s New page on update from the General tab in Settings.
        </p>
      </footer>
    </>
  );
}
